name: Deploy Jekyll site to GitHub Pages
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allow manual re-run from Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle lock --add-platform x86_64-linux
          bundle install --jobs 4 --retry 3
      - name: Build site
        run: |
          bundle exec jekyll build
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
